### ISSUE TITLE
Vagrant provision system issue

### ISSUE THREAD

**Issue by Covalt100** [rdbreak/rhcsa7env#1]
system: Running ansible-playbook...
ERROR! 'reboot' is not a valid attribute for a Play

The error appears to have been in '/Users/stuartmcmullen/bin/rhcsaenv/playbooks/system.yml': line 74, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    service: name=firewalld state=started
- name: Rebooting machine
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by rdbreak** [comment]
This should be fixed with the latest commit.
