### ISSUE TITLE
ipa server should provide nfs shares for users dave and lisa

### ISSUE THREAD

**Issue by Pigi-102** [rdbreak/rhcsa7env#10]
As shown in https://app.slack.com/docs/TGTE0EB5Z/FLTSDD9HB?origin_team=TGTE0EB5Z&origin_channel=CHDDTG4V6 there is an objective to have dave and lisa automatically mount home directories from ipa server ( and also be authenticated with it ). 
I managed to get partially done, by creating the shares on ipa server and use them ( also in nfs3 at the moment ) but being that in RHCSA7 there is an objective on this it would be better to have them already prepared on the server so it' s possible to accomplish point 7 of the indicated doc.

**Comment by rdbreak** [comment]
This should be fixed with the latest push. If you have Ansible installed on your host machine, you can run the `ipa.yml` playbook
