### ISSUE TITLE
Misc problems in Linux deployment

### ISSUE THREAD

**Issue by garyfritzz** [rdbreak/rhcsa7env#3]
Gave up on running in RHEL8 (no epel), reverted to CentOS7.
Downloaded vagrant & VirtualBox.

yum localinstall -y vagrant_2.2.5_x86_64.rpm    # works fine

vagrant plugin install vagrant-guest-ansible
_Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:
Unable to resolve dependency: user requested 'vagrant-guest-ansible (> 0)'_

sudo yum localinstall -y VirtualBox-6.0-6.0.10_132072_el7-1.x86_64.rpm 
((It complained that my system was not set up to build kernel modules, and I should install kernel-devel kerneld-devel-3.10.0.957.12.2.el7.x86_64.  I installed kernel-devel and it actually installed 27.2 instead of 12.2.  12.2 does not seem to be available.  But it still said I needed 12.2.  Finally I rebooted and tried running /bin/vboxconfig again, and that worked.  Guess it had to do some cleanup / config after I installed kernel-devel?))

vagrant up --provider virtualbox
Many happy green messages, until:
_==> ipa: Running provisioner: shell...
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using._

vagrant status
 _Current machine states:

ipa                       aborted (virtualbox)
repo                      not created (virtualbox)
system1                   not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`._ 

More or less by accident, I did a "vagrant up" and it took off again.  It's been running for over an hour now, slowly printing green "Package xxx will be installed" messages... 

The Linux VM (in VMware Player) is churning like mad, but I think it may be hung now.  I tried to pause the VM to see if restarting it would dislodge the stuck process, but I can't pause it.  It just keeps running.

EDIT:  No, it kept running for at least 3 hours.  Then I checked it about 4 hours after doing the second "vagrant up," and the VM is no longer sluggish/unresponsive.  The vagrant command is no longer consuming CPU -- but it never returned to a shell prompt either.

So it churned for about 3 hours, then just... stopped churning.  But it didn't exit the command.

EDIT 2:  The next morning, 14 hours later, it's still just sitting there.  ps -ef says vagrant is still running, but it hasn't done anything for the last 12-14 hours.

**Comment by rdbreak** [comment]
I noticed that the plugin you attempted to install was `vagrant-guest-ansible`, the plugin is named `vagrant-guest_ansible`. Can you try to install it and try again? Then run `vagrant destroy -f && git pull && vagrant up`

**Comment by rdbreak** [comment]
Should be fixed with latest [push](https://github.com/rdbreak/rhcsa7env/commit/83da154bf9a444db0e5e9a3c93458e7bcc07c534). Please check

**Comment by rdbreak** [comment]
Confirmed with user that latest push fixed their issue.
