### ISSUE TITLE
Failed to connect no route to host 192.168.55.4 port 22:  on Ubuntu machine

### ISSUE THREAD

**Issue by arunsoman12345** [rdbreak/rhcsa7env#8]
ASK [Setting Hostname] ********************************************************
fatal: [repo.example.com]: UNREACHABLE! => changed=false 
  msg: |-
    Data could not be sent to remote host "192.168.55.4". Make sure this host can be reached over ssh: ssh: connect to host 192.168.55.4 port 22: No route to host
  unreachable: true

**Comment by rdbreak** [comment]
I’ll take a look at this today

**Comment by rdbreak** [comment]
I set up this environment on my Ubuntu system and it set up without issue. Maybe try destroying and provisioning the environment once more? `vagrant destroy -f ; git pull ; vagrant up`
